### ISSUE TITLE
Expose configuration through _config.yml

### ISSUE THREAD

**Issue by skatkov** [crbelaus/jekyll-tailwind#8]
It would be great if this gem comes with reasonable defaults, but also provides a way to overwrite and tweak settings through `_config.yml` file.

As example, we currently expect that `assets/css/app.css` is present, but it's not really required. It's also possible that multiple input files could be provided and there is not support for that.

The suggested configuration format:

```yml
tailwind:
  input: ['assets/css/app.css'] # should support String or Array here, no default is needed.
  output: "_site/assets/css/app.css" # default's to "_site/assets/css/app.css", but it's possible to overwrite. Output is required.
  config: "config/tailwind.config.js" # default to 'tailwind.config.js'
  minify: true # default's to false
  postcss: "config/postcss.config.js" # defaults to "postcss.config.js", if files is present. 
```

All these settings will be passed to tailwindcss executable. Currently, we support `config_path`, but I support align naming with parameters for tailwindcss.

version is not required, since this will be configured through Gemfile with `tailwindcss-ruby` gem.
